### ISSUE TITLE
install with docker?

### ISSUE THREAD

**Issue by lzhengchun** [LLNL/msr-safe#58]
Does it work with Docker? If so, any clue on how to deploy it?

Thanks

**Comment by slabasan** [comment]
Great question @lzhengchun. I have not used Docker before, so I'm not quite sure. Let me look into this and get back to you.

**Comment by dianarg** [comment]
As far as I can tell, msr-safe needs to be installed in the host OS.  @lzhengchun do you have the ability to install kernel modules in the host OS?

I'd like to learn more about your use case because even if you can get it to work, I think it could lead to some unexpected behavior in cases where multiple containers are sharing the same hardware.

**Comment by lzhengchun** [comment]
@dianarg @slabasan  Thanks very much for your response! sorry for my silence. 

We want to do some evaluations using MSR (control energy consumption) but the resource provider does not want to give us root, so we though msr-safe should be a good option. BTW We used msr-safe at Argonne's Bebop machine. Thanks!

But the resource provider also does not want to install and configure msr-safe, they can only run docker for us -_-.

We also want to use [libmsr](https://github.com/LLNL/libmsr).  If we persuade them to install msr-safe, do you think if we can use libmsr with docker? 


Thanks
